### ISSUE TITLE
fix it

### ISSUE THREAD

**Issue by himadrinath** [dzimchuk/azure-ad-b2c-asp-net-core#1]
not working

**Comment by dzimchuk** [comment]
Hi, could you please elaborate?

**Comment by himadrinath** [comment]
when i click into sign in its redirecting to my b2c login page and instantly redirecting back to my localhost page

**Comment by himadrinath** [comment]
![problem](https://cloud.githubusercontent.com/assets/12247490/19957751/839ee888-a1bf-11e6-94f7-bb00a6e4b15a.gif)

**Comment by himadrinath** [comment]
its been fixed i submitted wrong redirect url in active directory b2c application.
https://localhost:44397/ and changed to https://localhost:44397/signin-oidc. its working now but getting another problem after successfully login getting a another error msg.

ArgumentNullException: Value cannot be null. Parameter name: ticket

**Comment by himadrinath** [comment]
![argumentnullexception](https://cloud.githubusercontent.com/assets/12247490/20035724/6079edf0-a415-11e6-91ac-81c80c70997f.gif)

**Comment by dzimchuk** [comment]
@himadrinath When the middleware issues a GET request to the authorize endpoint it passes a bunch of parameters such as policy name, etc. I don't see any of them in your demo...

**Comment by himadrinath** [comment]
@dzimchuk because i used opera thats why by default its not showing additional query parameters in address bar

**here it is on Chrome**

![ticket](https://cloud.githubusercontent.com/assets/12247490/20148951/0568d99a-a6d5-11e6-9c34-c8cc849a45d2.gif)

**Comment by himadrinath** [comment]
@dzimchuk **any news**

**Comment by dzimchuk** [comment]
@himadrinath Unfortunately I can't add much. I guess you want to debug the OpenID handler (https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L665) to figure out why it fails to create a ticket.

**Comment by PatLac04** [comment]
@dzimchuk So, is the conclusion that this sample will not work?

**Comment by dzimchuk** [comment]
@PatLac04 Well, the sample is fully functional if properly configured (including azure ad). Are you experiencing the same issue as @himadrinath?

**Comment by dzimchuk** [comment]
So I've noticed one thing, when you're redeeming an authorization code (OnAuthorizationCodeReceived) and there is an unhandled exception you end up with this vague error as @himadrinath demonstrated. You've got to handle these errors and log them. If you call context.HandleResponse() the user will be signed in but you won't have access token. With logging in place you should be able to identify the issue.

I've updated the sample to catch errors when redeeming the code.

**Comment by narenkv** [comment]
Your sample and your website gives a very good info on Azure AD B2C, However while using the sample I am getting the following error

This error is triggered when the sucessfull login is authenticated and the application redirects to https://localhost:44397/signin-oidc. Any idea which setting or code is missing. Could you please help us out

An unhandled exception occurred while processing the request.
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()

Stack Query Cookies Headers
NullReferenceException: Object reference not set to an instance of an object.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
