### ISSUE TITLE
Error: An item with the same key has already been added.

### ISSUE THREAD

**Issue by ryanbuening** [dzimchuk/azure-ad-b2c-asp-net-core#3]
Hello. I cloned the project and tried building and running it without making any configuration changes just to see if it would run. I'm getting the error below:

![image](https://cloud.githubusercontent.com/assets/812974/26251873/b6f8b314-3c7c-11e7-81cb-6a7d46f28e14.png)

Any ideas? Thanks.

**Comment by cheoalfredo** [comment]
dude, got any chance to fix this ?
