### ISSUE TITLE
Reason for cloning OpenIdConnectConfiguration in PolicyConfigurationManager.cs

### ISSUE THREAD

**Issue by oobayly** [dzimchuk/azure-ad-b2c-asp-net-core#4]
In https://github.com/dzimchuk/azure-ad-b2c-asp-net-core/blob/master/TestApp/Infrastructure/PolicyConfigurationManager.cs 

Is there any chance you explain the rationale behind cloning the OpenIdConnectConfiguration, and the manner in which you do it (serialising the configuration to json and back). I'm modifying your version to work with multiple Authorities and I'd like to understand why it's done like this.

Many thanks.

**Comment by oobayly** [comment]
Um, nix that request - As I've been rewriting my version (and with a fresh mind) I understand that you wouldn't want to starting merging configuration into the original manager.

As for the unsetting & setting the properties when cloning, I now realise that the serializer can't create an instance of Microsoft.IdentityModel.Tokens.SecurityKey as it's interface.

**Comment by dzimchuk** [comment]
@oobayly The whole idea behind a custom configuration manager was to support policy specific configurations. See also https://dzimchuk.net/setting-up-your-aspnet-core-apps-and-services-for-azure-ad-b2c/

Things might have changed since then.
